# Generated by Django 6.0.6 on 2026-07-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardattendance',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='GuardAssignment',
        ),
        migrations.DeleteModel(
            name='GuardAttendance',
        ),
    ]
