# Generated by Django 6.0.6 on 2026-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('leave', 'On Leave'), ('suspended', 'Suspended')], default='available', max_length=20),
        ),
    ]
