# Generated by Django 6.0.6 on 2026-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guard",
            name="hourly_pay_rate",
        ),
        migrations.AddField(
            model_name="guard",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guard",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guard",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guard",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
