# Generated by Django 6.0.6 on 2026-07-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_guard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('leave', 'On Leave'), ('suspended', 'Suspended')], default='available', max_length=20),
        ),
    ]
