# Generated by Django 6.0.6 on 2026-07-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0002_alter_guard_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateField()),
                ("relieved_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
