# Generated by Django 6.0.6 on 2026-07-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_remove_guard_hourly_pay_rate_guard_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuardAssignment',
        ),
    ]
