# Generated by Django 6.0.6 on 2026-07-15 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0003_guardassignment"),
        ("operation", "0002_remove_job_client_contract_delete_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardassignment",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="operation.contract",
            ),
        ),
        migrations.AddField(
            model_name="guardassignment",
            name="guard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="guard.guard",
            ),
        ),
    ]
