# Generated by Django 6.0.6 on 2026-07-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="job",
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
