# Generated by Django 6.0.6 on 2026-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="hourly_billing_rate",
        ),
    ]
