# Generated by Django 6.0.6 on 2026-07-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
