# Generated by Django 6.0.6 on 2026-07-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='client',
        ),
    ]
