# Generated by Django 6.0.6 on 2026-07-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_remove_billing_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="pdf",
        ),
    ]
