# Generated by Django 6.0.6 on 2026-07-20 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_remove_invoice_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="billing_date",
        ),
        migrations.AddField(
            model_name="billing",
            name="issue_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date this billing was generated.",
            ),
            preserve_default=False,
        ),
    ]
