# Generated by Django 6.0.6 on 2026-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_remove_billing_billing_date_billing_issue_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finances_in_status_e91c9f_idx",
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Bank transaction, OR number, check number, etc.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finances_pa_payment_1d61c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="finances_pa_status_173bd1_idx"),
        ),
    ]
