# Generated by Django 6.0.6 on 2026-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0005_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
