# Generated by Django 6.0.6 on 2026-07-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
