# Generated by Django 6.0.6 on 2026-07-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="contracts/documents/")),
                ("remarks", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contract Document",
                "verbose_name_plural": "Contract Documents",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("custom", "Custom"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("monthly_fixed", "Monthly Fixed"),
                    ("custom", "Custom"),
                ],
                default="monthly_fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("due_on_receipt", "Due on Receipt"),
                    ("net_7", "Net 7 Days"),
                    ("net_15", "Net 15 Days"),
                    ("net_30", "Net 30 Days"),
                    ("custom", "Custom"),
                ],
                default="net_30",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate according to the selected billing type.",
                max_digits=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax percentage applied to billings.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="number_of_guards",
            field=models.PositiveIntegerField(
                default=1, help_text="Required number of guards."
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="remarks",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status"], name="contract_co_status_601477_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["start_date"], name="contract_co_start_d_534980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["end_date"], name="contract_co_end_dat_c9055c_idx"
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="contract.contract",
            ),
        ),
    ]
