# Generated by Django 6.0.6 on 2026-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractdocument_contract_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate according to the selected billing type.', max_digits=12, null=True),
        ),
    ]
