# Generated by Django 6.0.6 on 2026-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="unique_guard_deployment",
        ),
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ENDED", "Ended"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="is_active",
        ),
    ]
